version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: simple_app_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/simple_app_dev
      PHX_SERVER: "true"
      SECRET_KEY_BASE: dev-secret-key-base-that-is-at-least-64-bytes-long-for-development-use-only
    ports:
      - "4000:80"
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "mix ecto.setup && mix phx.server"

volumes:
  postgres_data: