{application,circular_buffer,
             [{modules,['Elixir.CircularBuffer',
                        'Elixir.Collectable.CircularBuffer',
                        'Elixir.Enumerable.CircularBuffer',
                        'Elixir.Inspect.CircularBuffer']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir]},
              {description,"General purpose circular buffer"},
              {registered,[]},
              {vsn,"0.4.2"}]}.
